Added hackstetson 2018
floridahackers/fh-platform pull request #14
Opened 2018-03-12 05:32 UTC by ericakok

Adding hackstetson 2018

2018-03-12 14:36 UTC, jalvarado91 requested changes

2018-03-12 14:36 UTC, jalvarado91 commented on src/all_events.js
> +    }
Can we add a  comma here? Otherwise the site will break.

2018-03-13 00:20 UTC, ericakok reviewed
added comma

2018-03-13 00:27 UTC, merged

2018-03-13 00:27 UTC, jalvarado91 commented
🎉