Social media links are added at the footer and a heart with puls
floridahackers/fh-platform pull request #7
Opened 2017-10-01 04:07 UTC by garg-ravi24

I have added the social media links on footer and a message that says "Made with <3 by Florida Hackers", as you have asked.
![screenshot 8](https://user-images.githubusercontent.com/31215399/31051664-0c7cfb50-a68c-11e7-8351-154f53af2201.png)

2017-10-02 04:13 UTC, jalvarado91 requested changes

2017-10-02 04:13 UTC, jalvarado91 commented on public/index.html
> +        <link rel="stylesheet" href="dist/styles.css" type="text/css" />
We shouldn't need to remove the slash or it'll break in prod.

2017-10-02 04:13 UTC, jalvarado91 commented on public/dist/styles.css
>   *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,
Generally we don't want to modify the dist files, as they get built by Travis. Can you put these changes in one of the SASS files? Inside the `home.scss` file might be a good place.

2017-10-02 07:58 UTC, garg-ravi24 commented
Can you please tell me how i can add these changes to scss file. I don't have knowledge about scss files.

2017-10-05 23:59 UTC, jalvarado91 requested changes

2017-10-05 23:59 UTC, jalvarado91 commented on npm-debug.log
> +0 info it worked if it ends with ok
Can you remove this file? This shouldn't be in this codebase

2017-10-05 23:59 UTC, jalvarado91 commented on prepros-6.config
> +{
Remove this file too.

2017-10-06 03:01 UTC, jalvarado91 approved these changes
Looks good!

![](https://media.giphy.com/media/s2qXK8wAvkHTO/giphy.gif)

2017-10-06 03:02 UTC, merged